services:
  audiobookshelf-lubimyczytac-scrapper:
    image: ghcr.io/craftwork2720/audiobookshelf-audioteka:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - LANGUAGE=pl
      - MAX_RESULTS=15
      - ADD_AUDIOTEKA_LINK_TO_DESCRIPTION=true
    restart: unless-stopped