services:
  audiobookshelf-audioteka-scrapper:
    image: ghcr.io/craftwork2720/audiobookshelf-audioteka:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - LANGUAGE=pl
      - MAX_RESULTS=15
      - ADD_AUDIOTEKA_LINK_TO_DESCRIPTION=true
      - MIN_SCORE_THRESHOLD=150  # Minimalny wynik dopasowania
      - STRICT_MATCHING=true     # Włączenie ostrego filtrowania
    restart: unless-stopped